### ISSUE TITLE
The /my/conf path for Docker

### ISSUE THREAD

**Issue by VirajAttanayake** [nordic-institute/REST-adapter-service#18]
Hi,

Im trying to install rest-api-gateway using docker. However the container does not have a path /my/conf  in the build and giving below error.

docker run -p 8080:8080 -v /host/dir/conf:/my/conf -e "JAVA_OPTS=-DpropertiesDirectory=/my/conf"  rest-adapter-service

```
java.io.FileNotFoundException: /my/conf/provider-gateway.properties (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_111]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_111]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_111]
        at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[na:1.8.0_111]
        at org.niis.xrd4j.common.util.PropertiesUtil.load(PropertiesUtil.java:101) ~[common-0.3.0.jar!/:na]
        at org.niis.xroad.restadapterservice.ProviderGateway.init(ProviderGateway.java:95) [classes!/:1.1.0-SNAPSHOT]
        at javax.servlet.GenericServlet.init(GenericServlet.java:158) [tomcat-embed-core-9.0.37.jar!/:4.0.FR]
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:986) [tomcat-embed-core-9.0.37.jar!/:9.0.37]
        at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.load(TomcatEmbeddedContext.java:82) [spring-boot-2.3.3.RELEASE.jar!/:2.3.3.RELEASE]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_111]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_111]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_111]

```

**Comment by petkivim** [comment]
Hi @VirajAttanayake 

Have you placed a copy of the `provider-gateway.properties` file in the `/host/dir/conf` directory on your host? In this case, the absolute path of the config file is `/host/dir/conf/provider-gateway.properties`. And are the file and the directory accessible by the container?

**Comment by VirajAttanayake** [comment]
Hi Petteri,

Yes, I mixed up the host side and container side. 

Regards
Viraj
